name: Token ATM GitHub Pages CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # https://www.rupeshtiwari.com/setup-ci-cd-for-angular-app-with-github-action/#update-github-actions-to-deploy-angular-app
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Pre-Deployment check
        run: |
          npm run check

      - name: Build Angular project
        run: |
          npm build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: yongkanm/token-atm
          folder: dist
          force: false
          token: ${{ secrets.PAGE_REPO_TOKEN }} # TODO: GitHub Pages Deployment (require secret to be setup (PAT for the public repo))
